export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const PRODUCTS_LOAD_FAIL = "PRODUCTS_LOAD_FAIL";

export const GET_PRODUCT = "GET_PRODUCT";

export const REVIEWS_LOADED = "LOAD_REVIEW";
export const REVIEWS_LOAD_FAILED = "REVIEWS_LOAD_FAILED";

export const ADDED_TO_CART = "ADDED_TO_CART";
export const CART_ADD_FAILED = "CART_ADD_FAILED";

export const PRODUCT_ALREADY_IN_CART = "PRODUCT_ALREADY_IN_CART";
export const PRODUCT_NOT_IN_CART = "PRODUCT_NOT_IN_CART";

export const LOGOUT = "LOGOUT";
